// <auto-generated />
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataAccess.Entities.CoffeShop", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("CoffeShops");

                    b.HasData(
                        new
                        {
                            Id = "239ba06b-389b-4bd8-b656-49bf1dfae01c",
                            Address = "12 - Duy Tan - Ha Noi",
                            Name = "Ume",
                            OpeningHours = "7.00 Am"
                        },
                        new
                        {
                            Id = "3db25205-d340-4b25-a8e3-2f2f2e75e681",
                            Address = "19 - Pham Van Dong - Ha Noi",
                            Name = "Matchas",
                            OpeningHours = "7.00 Am"
                        },
                        new
                        {
                            Id = "ed3b07c5-fe83-4ea0-b97f-906776aea217",
                            Address = "52 - Nguyen Van Huyen - Ha Noi",
                            Name = "King Top",
                            OpeningHours = "7.00 Am"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
